test

diff --git a/dotnet-prettier/.git-hooks/pre-commit b/dotnet-prettier/.git-hooks/pre-commit
--- a/dotnet-prettier/.git-hooks/pre-commit
+++ b/dotnet-prettier/.git-hooks/pre-commit
@@ -1,3 +1,12 @@
 #!/bin/sh
 
-echo "[dotnet-format] pre-commit"
+# format
+echo -e "${YELLOW}Running pre-commit hook, dotnet format...${NC}"
+dotnet format --no-restore --verbosity detailed
+rc=$?
+if [[ $rc != 0 ]] ; then
+    echo -e "${RED}Failed to format project, please fix this and commit again${NC}"
+    exit $rc
+fi
+
+exit 0
